import "./01-practica/ejercicio.js";
import "./02-entregables/ejercicio-01.js";
import "./02-entregables/ejercicio-02.js";
import "./02-entregables/ejercicio-03.js";
import "./02-entregables/ejercicio-04.js";
import "./02-entregables/ejercicio-05.js";
import "./03-retos/ejercicio-06.js";
import "./03-retos/ejercicio-05.js";
import "./03-retos/ejercicio-04.js";
import "./03-retos/ejercicio-03.js";
import "./03-retos/ejercicio-02.js";
import "./03-retos/ejercicio-01.js";
console.log("Welcome to Exercises Playground.");
